# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  hrwebapi:
    image: hrwebapi
    build:
      context: .
      dockerfile: Hr.WebAPI/Dockerfile
    ports:
      - 5299:5299
